# Generated by Django 4.0.4 on 2022-07-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxie', '0002_delete_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxie',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
