# Generated by Django 4.0.4 on 2022-04-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_course_alter_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='profile_pic',
        ),
    ]
