# Generated by Django 4.0.4 on 2022-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
