# Generated by Django 4.0.4 on 2022-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.IntegerField(default=0),
        ),
    ]
