# Generated by Django 4.0.4 on 2022-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=40),
        ),
    ]
