# Generated by Django 4.0.4 on 2022-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_pic',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='teacher_pics'),
        ),
    ]
