# Generated by Django 4.0.4 on 2022-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0005_rename_departments_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
