# Generated by Django 4.0.4 on 2022-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0006_alter_department_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
