# Generated by Django 4.0.4 on 2022-05-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_course'),
        ('demo_site', '0007_alter_department_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.IntegerField(default=0)),
                ('teaching', models.IntegerField(default=0)),
                ('demanding', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_site.teacher')),
            ],
        ),
    ]
