# Generated by Django 4.0.4 on 2022-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0010_alter_vote_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='communication_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='demanding_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
