# Generated by Django 4.0.4 on 2022-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0012_rename_teacher_pic_teacher_teacher_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_src',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
