# Generated by Django 4.0.4 on 2022-05-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0016_alter_teacher_teacher_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='communication_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='demanding_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
