# Generated by Django 4.0.4 on 2022-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0018_commentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_pics'),
        ),
    ]
