# Generated by Django 4.0.4 on 2022-05-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0020_remove_vote_profile_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanswer',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo_site.teacher'),
            preserve_default=False,
        ),
    ]
