# Generated by Django 4.0.4 on 2022-05-14 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_site', '0021_commentanswer_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('pines'), to=settings.AUTH_USER_MODEL),
        ),
    ]
