# Generated by Django 4.0.4 on 2022-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0028_remove_teacher_department_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='communication_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='demanding_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching_average',
            field=models.FloatField(default=0.0),
        ),
    ]
