# Generated by Django 4.0.4 on 2022-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0030_alter_commentanswer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_img',
            field=models.ImageField(blank=True, default='teacher.jpg', null=True, upload_to='teacher_pics'),
        ),
    ]
