# Generated by Django 4.0.4 on 2022-05-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0033_remove_comment_likes_likebutton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likebutton',
            name='content',
        ),
        migrations.AddField(
            model_name='likebutton',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo_site.comment'),
        ),
    ]
