# Generated by Django 4.0.4 on 2022-05-16 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_site', '0035_rename_likes_likebutton_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanswer',
            name='dislikes',
            field=models.ManyToManyField(related_name='comment_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentanswer',
            name='likes',
            field=models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
