# Generated by Django 4.0.4 on 2022-05-16 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_site', '0036_commentanswer_dislikes_commentanswer_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentanswer',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='commentanswer',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(related_name='comment_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
