# Generated by Django 4.0.4 on 2022-05-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0037_remove_commentanswer_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
