# Generated by Django 4.0.4 on 2022-05-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0040_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='likes', to='demo_site.department'),
        ),
    ]
