# Generated by Django 4.0.4 on 2022-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0041_teacher_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='test',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
