# Generated by Django 4.0.4 on 2022-05-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0042_remove_teacher_test_comment_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_liked',
        ),
    ]
