# Generated by Django 4.0.4 on 2022-05-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0045_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentanswer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerFor', to='demo_site.comment'),
        ),
    ]
