# Generated by Django 4.0.4 on 2022-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0046_alter_commentanswer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
