# Generated by Django 4.0.4 on 2022-06-23 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0047_comment_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_for', to='demo_site.teacher'),
        ),
    ]
