# Generated by Django 4.0.4 on 2022-06-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0049_alter_comment_author_alter_comment_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromDepartment', to='demo_site.department'),
        ),
    ]
