# Generated by Django 4.0.4 on 2022-06-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
