# Generated by Django 4.0.4 on 2022-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle_test', '0005_remove_answer_question_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='moodle_test.answer'),
        ),
    ]
